/*
 * This file is generated by jOOQ.
 */
package be.rubus.microstream.performance.jooq.model;


import be.rubus.microstream.performance.jooq.model.tables.TripDetails;
import be.rubus.microstream.performance.jooq.model.tables.records.TripDetailsRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TripDetailsRecord> TRIP_DETAILS_PKEY = Internal.createUniqueKey(TripDetails.TRIP_DETAILS, DSL.name("trip_details_pkey"), new TableField[] { TripDetails.TRIP_DETAILS.TRIPID }, true);
}
