/*
 * This file is generated by jOOQ.
 */
package be.rubus.microstream.performance.jooq.model;


import be.rubus.microstream.performance.jooq.model.tables.TripDetails;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.trip_details</code>.
     */
    public final TripDetails TRIP_DETAILS = TripDetails.TRIP_DETAILS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            TripDetails.TRIP_DETAILS
        );
    }
}
