/*
 * This file is generated by jOOQ.
 */
package be.rubus.microstream.performance.jooq.model;


import be.rubus.microstream.performance.jooq.model.tables.TripDetails;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.trip_details</code>.
     */
    public static final TripDetails TRIP_DETAILS = TripDetails.TRIP_DETAILS;
}
