/*
 * This file is generated by jOOQ.
 */
package be.rubus.microstream.performance.jooq.model;


import be.rubus.microstream.performance.jooq.model.tables.Purchase;
import be.rubus.microstream.performance.jooq.model.tables.Purchaseitem;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_PURCHASE_CUSTOMER_ID = Internal.createIndex(DSL.name("idx_purchase_customer_id"), Purchase.PURCHASE, new OrderField[] { Purchase.PURCHASE.CUSTOMER_ID }, false);
    public static final Index IDX_PURCHASE_EMPLOYEE_ID = Internal.createIndex(DSL.name("idx_purchase_employee_id"), Purchase.PURCHASE, new OrderField[] { Purchase.PURCHASE.EMPLOYEE_ID }, false);
    public static final Index IDX_PURCHASE_ITEM_PURCHASE_ID = Internal.createIndex(DSL.name("idx_purchase_item_purchase_id"), Purchaseitem.PURCHASEITEM, new OrderField[] { Purchaseitem.PURCHASEITEM.PURCHASE_ID }, false);
    public static final Index IDX_PURCHASE_SHOP_ID = Internal.createIndex(DSL.name("idx_purchase_shop_id"), Purchase.PURCHASE, new OrderField[] { Purchase.PURCHASE.SHOP_ID }, false);
    public static final Index IDX_PURCHASE_TIME_STAMP = Internal.createIndex(DSL.name("idx_purchase_time_stamp"), Purchase.PURCHASE, new OrderField[] { Purchase.PURCHASE.TIME_STAMP }, false);
}
