/*
 * This file is generated by jOOQ.
 */
package be.rubus.microstream.performance.jooq.model;


import be.rubus.microstream.performance.jooq.model.tables.*;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.address</code>.
     */
    public static final Address ADDRESS = Address.ADDRESS;

    /**
     * The table <code>public.author</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>public.book</code>.
     */
    public static final Book BOOK = Book.BOOK;

    /**
     * The table <code>public.city</code>.
     */
    public static final City CITY = City.CITY;

    /**
     * The table <code>public.country</code>.
     */
    public static final Country COUNTRY = Country.COUNTRY;

    /**
     * The table <code>public.customer</code>.
     */
    public static final Customer CUSTOMER = Customer.CUSTOMER;

    /**
     * The table <code>public.employee</code>.
     */
    public static final Employee EMPLOYEE = Employee.EMPLOYEE;

    /**
     * The table <code>public.genre</code>.
     */
    public static final Genre GENRE = Genre.GENRE;

    /**
     * The table <code>public.inventoryitem</code>.
     */
    public static final Inventoryitem INVENTORYITEM = Inventoryitem.INVENTORYITEM;

    /**
     * The table <code>public.language</code>.
     */
    public static final Language LANGUAGE = Language.LANGUAGE;

    /**
     * The table <code>public.publisher</code>.
     */
    public static final Publisher PUBLISHER = Publisher.PUBLISHER;

    /**
     * The table <code>public.purchase</code>.
     */
    public static final Purchase PURCHASE = Purchase.PURCHASE;

    /**
     * The table <code>public.purchaseitem</code>.
     */
    public static final Purchaseitem PURCHASEITEM = Purchaseitem.PURCHASEITEM;

    /**
     * The table <code>public.shop</code>.
     */
    public static final Shop SHOP = Shop.SHOP;

    /**
     * The table <code>public.state</code>.
     */
    public static final State STATE = State.STATE;
}
