/*
 * This file is generated by jOOQ.
 */
package be.rubus.microstream.performance.jooq.model.tables.records;


import be.rubus.microstream.performance.jooq.model.tables.Inventoryitem;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InventoryitemRecord extends UpdatableRecordImpl<InventoryitemRecord> implements Record4<Long, Integer, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.inventoryitem.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.inventoryitem.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.inventoryitem.amount</code>.
     */
    public void setAmount(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.inventoryitem.amount</code>.
     */
    public Integer getAmount() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.inventoryitem.book_id</code>.
     */
    public void setBookId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.inventoryitem.book_id</code>.
     */
    public Long getBookId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.inventoryitem.shop_id</code>.
     */
    public void setShopId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.inventoryitem.shop_id</code>.
     */
    public Long getShopId() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, Integer, Long, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, Integer, Long, Long> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Inventoryitem.INVENTORYITEM.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Inventoryitem.INVENTORYITEM.AMOUNT;
    }

    @Override
    public Field<Long> field3() {
        return Inventoryitem.INVENTORYITEM.BOOK_ID;
    }

    @Override
    public Field<Long> field4() {
        return Inventoryitem.INVENTORYITEM.SHOP_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getAmount();
    }

    @Override
    public Long component3() {
        return getBookId();
    }

    @Override
    public Long component4() {
        return getShopId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getAmount();
    }

    @Override
    public Long value3() {
        return getBookId();
    }

    @Override
    public Long value4() {
        return getShopId();
    }

    @Override
    public InventoryitemRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public InventoryitemRecord value2(Integer value) {
        setAmount(value);
        return this;
    }

    @Override
    public InventoryitemRecord value3(Long value) {
        setBookId(value);
        return this;
    }

    @Override
    public InventoryitemRecord value4(Long value) {
        setShopId(value);
        return this;
    }

    @Override
    public InventoryitemRecord values(Long value1, Integer value2, Long value3, Long value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InventoryitemRecord
     */
    public InventoryitemRecord() {
        super(Inventoryitem.INVENTORYITEM);
    }

    /**
     * Create a detached, initialised InventoryitemRecord
     */
    public InventoryitemRecord(Long id, Integer amount, Long bookId, Long shopId) {
        super(Inventoryitem.INVENTORYITEM);

        setId(id);
        setAmount(amount);
        setBookId(bookId);
        setShopId(shopId);
    }
}
