/*
 * This file is generated by jOOQ.
 */
package be.rubus.microstream.performance.jooq.model.tables.records;


import be.rubus.microstream.performance.jooq.model.tables.Purchase;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PurchaseRecord extends UpdatableRecordImpl<PurchaseRecord> implements Record5<Long, LocalDateTime, Long, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.purchase.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.purchase.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.purchase.time_stamp</code>.
     */
    public void setTimeStamp(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.purchase.time_stamp</code>.
     */
    public LocalDateTime getTimeStamp() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.purchase.customer_id</code>.
     */
    public void setCustomerId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.purchase.customer_id</code>.
     */
    public Long getCustomerId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.purchase.employee_id</code>.
     */
    public void setEmployeeId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.purchase.employee_id</code>.
     */
    public Long getEmployeeId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.purchase.shop_id</code>.
     */
    public void setShopId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.purchase.shop_id</code>.
     */
    public Long getShopId() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, LocalDateTime, Long, Long, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, LocalDateTime, Long, Long, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Purchase.PURCHASE.ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return Purchase.PURCHASE.TIME_STAMP;
    }

    @Override
    public Field<Long> field3() {
        return Purchase.PURCHASE.CUSTOMER_ID;
    }

    @Override
    public Field<Long> field4() {
        return Purchase.PURCHASE.EMPLOYEE_ID;
    }

    @Override
    public Field<Long> field5() {
        return Purchase.PURCHASE.SHOP_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getTimeStamp();
    }

    @Override
    public Long component3() {
        return getCustomerId();
    }

    @Override
    public Long component4() {
        return getEmployeeId();
    }

    @Override
    public Long component5() {
        return getShopId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getTimeStamp();
    }

    @Override
    public Long value3() {
        return getCustomerId();
    }

    @Override
    public Long value4() {
        return getEmployeeId();
    }

    @Override
    public Long value5() {
        return getShopId();
    }

    @Override
    public PurchaseRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public PurchaseRecord value2(LocalDateTime value) {
        setTimeStamp(value);
        return this;
    }

    @Override
    public PurchaseRecord value3(Long value) {
        setCustomerId(value);
        return this;
    }

    @Override
    public PurchaseRecord value4(Long value) {
        setEmployeeId(value);
        return this;
    }

    @Override
    public PurchaseRecord value5(Long value) {
        setShopId(value);
        return this;
    }

    @Override
    public PurchaseRecord values(Long value1, LocalDateTime value2, Long value3, Long value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PurchaseRecord
     */
    public PurchaseRecord() {
        super(Purchase.PURCHASE);
    }

    /**
     * Create a detached, initialised PurchaseRecord
     */
    public PurchaseRecord(Long id, LocalDateTime timeStamp, Long customerId, Long employeeId, Long shopId) {
        super(Purchase.PURCHASE);

        setId(id);
        setTimeStamp(timeStamp);
        setCustomerId(customerId);
        setEmployeeId(employeeId);
        setShopId(shopId);
    }
}
