/*
 * This file is generated by jOOQ.
 */
package be.rubus.microstream.performance.jooq.model.tables.records;


import be.rubus.microstream.performance.jooq.model.tables.State;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StateRecord extends UpdatableRecordImpl<StateRecord> implements Record3<Long, String, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.state.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.state.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.state.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.state.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.state.country_id</code>.
     */
    public void setCountryId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.state.country_id</code>.
     */
    public Long getCountryId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, String, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, String, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return State.STATE.ID;
    }

    @Override
    public Field<String> field2() {
        return State.STATE.NAME;
    }

    @Override
    public Field<Long> field3() {
        return State.STATE.COUNTRY_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Long component3() {
        return getCountryId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Long value3() {
        return getCountryId();
    }

    @Override
    public StateRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public StateRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public StateRecord value3(Long value) {
        setCountryId(value);
        return this;
    }

    @Override
    public StateRecord values(Long value1, String value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StateRecord
     */
    public StateRecord() {
        super(State.STATE);
    }

    /**
     * Create a detached, initialised StateRecord
     */
    public StateRecord(Long id, String name, Long countryId) {
        super(State.STATE);

        setId(id);
        setName(name);
        setCountryId(countryId);
    }
}
