/*
 * This file is generated by jOOQ.
 */
package be.rubus.microstream.performance.jooq.model.tables.records;


import be.rubus.microstream.performance.jooq.model.tables.TripDetails;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record19;
import org.jooq.Row19;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TripDetailsRecord extends UpdatableRecordImpl<TripDetailsRecord> implements Record19<String, Float, Float, LocalDateTime, String, Float, Float, Float, Float, Short, Short, LocalDateTime, String, Short, String, Float, Float, Float, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.trip_details.tripid</code>.
     */
    public void setTripid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.trip_details.tripid</code>.
     */
    public String getTripid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.trip_details.congestionsurcharge</code>.
     */
    public void setCongestionsurcharge(Float value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.trip_details.congestionsurcharge</code>.
     */
    public Float getCongestionsurcharge() {
        return (Float) get(1);
    }

    /**
     * Setter for <code>public.trip_details.distance</code>.
     */
    public void setDistance(Float value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.trip_details.distance</code>.
     */
    public Float getDistance() {
        return (Float) get(2);
    }

    /**
     * Setter for <code>public.trip_details.dropoffdatetime</code>.
     */
    public void setDropoffdatetime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.trip_details.dropoffdatetime</code>.
     */
    public LocalDateTime getDropoffdatetime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.trip_details.dropofflocationid</code>.
     */
    public void setDropofflocationid(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.trip_details.dropofflocationid</code>.
     */
    public String getDropofflocationid() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.trip_details.extraamount</code>.
     */
    public void setExtraamount(Float value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.trip_details.extraamount</code>.
     */
    public Float getExtraamount() {
        return (Float) get(5);
    }

    /**
     * Setter for <code>public.trip_details.fareamount</code>.
     */
    public void setFareamount(Float value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.trip_details.fareamount</code>.
     */
    public Float getFareamount() {
        return (Float) get(6);
    }

    /**
     * Setter for <code>public.trip_details.improvementsurcharge</code>.
     */
    public void setImprovementsurcharge(Float value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.trip_details.improvementsurcharge</code>.
     */
    public Float getImprovementsurcharge() {
        return (Float) get(7);
    }

    /**
     * Setter for <code>public.trip_details.mtatax</code>.
     */
    public void setMtatax(Float value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.trip_details.mtatax</code>.
     */
    public Float getMtatax() {
        return (Float) get(8);
    }

    /**
     * Setter for <code>public.trip_details.passengercount</code>.
     */
    public void setPassengercount(Short value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.trip_details.passengercount</code>.
     */
    public Short getPassengercount() {
        return (Short) get(9);
    }

    /**
     * Setter for <code>public.trip_details.paymenttype</code>.
     */
    public void setPaymenttype(Short value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.trip_details.paymenttype</code>.
     */
    public Short getPaymenttype() {
        return (Short) get(10);
    }

    /**
     * Setter for <code>public.trip_details.pickupdatetime</code>.
     */
    public void setPickupdatetime(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.trip_details.pickupdatetime</code>.
     */
    public LocalDateTime getPickupdatetime() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>public.trip_details.pickuplocationid</code>.
     */
    public void setPickuplocationid(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.trip_details.pickuplocationid</code>.
     */
    public String getPickuplocationid() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.trip_details.ratecodeid</code>.
     */
    public void setRatecodeid(Short value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.trip_details.ratecodeid</code>.
     */
    public Short getRatecodeid() {
        return (Short) get(13);
    }

    /**
     * Setter for <code>public.trip_details.storeandfwdflag</code>.
     */
    public void setStoreandfwdflag(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.trip_details.storeandfwdflag</code>.
     */
    public String getStoreandfwdflag() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.trip_details.tipamount</code>.
     */
    public void setTipamount(Float value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.trip_details.tipamount</code>.
     */
    public Float getTipamount() {
        return (Float) get(15);
    }

    /**
     * Setter for <code>public.trip_details.tollamount</code>.
     */
    public void setTollamount(Float value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.trip_details.tollamount</code>.
     */
    public Float getTollamount() {
        return (Float) get(16);
    }

    /**
     * Setter for <code>public.trip_details.totalamount</code>.
     */
    public void setTotalamount(Float value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.trip_details.totalamount</code>.
     */
    public Float getTotalamount() {
        return (Float) get(17);
    }

    /**
     * Setter for <code>public.trip_details.vendorid</code>.
     */
    public void setVendorid(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.trip_details.vendorid</code>.
     */
    public String getVendorid() {
        return (String) get(18);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record19 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row19<String, Float, Float, LocalDateTime, String, Float, Float, Float, Float, Short, Short, LocalDateTime, String, Short, String, Float, Float, Float, String> fieldsRow() {
        return (Row19) super.fieldsRow();
    }

    @Override
    public Row19<String, Float, Float, LocalDateTime, String, Float, Float, Float, Float, Short, Short, LocalDateTime, String, Short, String, Float, Float, Float, String> valuesRow() {
        return (Row19) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return TripDetails.TRIP_DETAILS.TRIPID;
    }

    @Override
    public Field<Float> field2() {
        return TripDetails.TRIP_DETAILS.CONGESTIONSURCHARGE;
    }

    @Override
    public Field<Float> field3() {
        return TripDetails.TRIP_DETAILS.DISTANCE;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return TripDetails.TRIP_DETAILS.DROPOFFDATETIME;
    }

    @Override
    public Field<String> field5() {
        return TripDetails.TRIP_DETAILS.DROPOFFLOCATIONID;
    }

    @Override
    public Field<Float> field6() {
        return TripDetails.TRIP_DETAILS.EXTRAAMOUNT;
    }

    @Override
    public Field<Float> field7() {
        return TripDetails.TRIP_DETAILS.FAREAMOUNT;
    }

    @Override
    public Field<Float> field8() {
        return TripDetails.TRIP_DETAILS.IMPROVEMENTSURCHARGE;
    }

    @Override
    public Field<Float> field9() {
        return TripDetails.TRIP_DETAILS.MTATAX;
    }

    @Override
    public Field<Short> field10() {
        return TripDetails.TRIP_DETAILS.PASSENGERCOUNT;
    }

    @Override
    public Field<Short> field11() {
        return TripDetails.TRIP_DETAILS.PAYMENTTYPE;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return TripDetails.TRIP_DETAILS.PICKUPDATETIME;
    }

    @Override
    public Field<String> field13() {
        return TripDetails.TRIP_DETAILS.PICKUPLOCATIONID;
    }

    @Override
    public Field<Short> field14() {
        return TripDetails.TRIP_DETAILS.RATECODEID;
    }

    @Override
    public Field<String> field15() {
        return TripDetails.TRIP_DETAILS.STOREANDFWDFLAG;
    }

    @Override
    public Field<Float> field16() {
        return TripDetails.TRIP_DETAILS.TIPAMOUNT;
    }

    @Override
    public Field<Float> field17() {
        return TripDetails.TRIP_DETAILS.TOLLAMOUNT;
    }

    @Override
    public Field<Float> field18() {
        return TripDetails.TRIP_DETAILS.TOTALAMOUNT;
    }

    @Override
    public Field<String> field19() {
        return TripDetails.TRIP_DETAILS.VENDORID;
    }

    @Override
    public String component1() {
        return getTripid();
    }

    @Override
    public Float component2() {
        return getCongestionsurcharge();
    }

    @Override
    public Float component3() {
        return getDistance();
    }

    @Override
    public LocalDateTime component4() {
        return getDropoffdatetime();
    }

    @Override
    public String component5() {
        return getDropofflocationid();
    }

    @Override
    public Float component6() {
        return getExtraamount();
    }

    @Override
    public Float component7() {
        return getFareamount();
    }

    @Override
    public Float component8() {
        return getImprovementsurcharge();
    }

    @Override
    public Float component9() {
        return getMtatax();
    }

    @Override
    public Short component10() {
        return getPassengercount();
    }

    @Override
    public Short component11() {
        return getPaymenttype();
    }

    @Override
    public LocalDateTime component12() {
        return getPickupdatetime();
    }

    @Override
    public String component13() {
        return getPickuplocationid();
    }

    @Override
    public Short component14() {
        return getRatecodeid();
    }

    @Override
    public String component15() {
        return getStoreandfwdflag();
    }

    @Override
    public Float component16() {
        return getTipamount();
    }

    @Override
    public Float component17() {
        return getTollamount();
    }

    @Override
    public Float component18() {
        return getTotalamount();
    }

    @Override
    public String component19() {
        return getVendorid();
    }

    @Override
    public String value1() {
        return getTripid();
    }

    @Override
    public Float value2() {
        return getCongestionsurcharge();
    }

    @Override
    public Float value3() {
        return getDistance();
    }

    @Override
    public LocalDateTime value4() {
        return getDropoffdatetime();
    }

    @Override
    public String value5() {
        return getDropofflocationid();
    }

    @Override
    public Float value6() {
        return getExtraamount();
    }

    @Override
    public Float value7() {
        return getFareamount();
    }

    @Override
    public Float value8() {
        return getImprovementsurcharge();
    }

    @Override
    public Float value9() {
        return getMtatax();
    }

    @Override
    public Short value10() {
        return getPassengercount();
    }

    @Override
    public Short value11() {
        return getPaymenttype();
    }

    @Override
    public LocalDateTime value12() {
        return getPickupdatetime();
    }

    @Override
    public String value13() {
        return getPickuplocationid();
    }

    @Override
    public Short value14() {
        return getRatecodeid();
    }

    @Override
    public String value15() {
        return getStoreandfwdflag();
    }

    @Override
    public Float value16() {
        return getTipamount();
    }

    @Override
    public Float value17() {
        return getTollamount();
    }

    @Override
    public Float value18() {
        return getTotalamount();
    }

    @Override
    public String value19() {
        return getVendorid();
    }

    @Override
    public TripDetailsRecord value1(String value) {
        setTripid(value);
        return this;
    }

    @Override
    public TripDetailsRecord value2(Float value) {
        setCongestionsurcharge(value);
        return this;
    }

    @Override
    public TripDetailsRecord value3(Float value) {
        setDistance(value);
        return this;
    }

    @Override
    public TripDetailsRecord value4(LocalDateTime value) {
        setDropoffdatetime(value);
        return this;
    }

    @Override
    public TripDetailsRecord value5(String value) {
        setDropofflocationid(value);
        return this;
    }

    @Override
    public TripDetailsRecord value6(Float value) {
        setExtraamount(value);
        return this;
    }

    @Override
    public TripDetailsRecord value7(Float value) {
        setFareamount(value);
        return this;
    }

    @Override
    public TripDetailsRecord value8(Float value) {
        setImprovementsurcharge(value);
        return this;
    }

    @Override
    public TripDetailsRecord value9(Float value) {
        setMtatax(value);
        return this;
    }

    @Override
    public TripDetailsRecord value10(Short value) {
        setPassengercount(value);
        return this;
    }

    @Override
    public TripDetailsRecord value11(Short value) {
        setPaymenttype(value);
        return this;
    }

    @Override
    public TripDetailsRecord value12(LocalDateTime value) {
        setPickupdatetime(value);
        return this;
    }

    @Override
    public TripDetailsRecord value13(String value) {
        setPickuplocationid(value);
        return this;
    }

    @Override
    public TripDetailsRecord value14(Short value) {
        setRatecodeid(value);
        return this;
    }

    @Override
    public TripDetailsRecord value15(String value) {
        setStoreandfwdflag(value);
        return this;
    }

    @Override
    public TripDetailsRecord value16(Float value) {
        setTipamount(value);
        return this;
    }

    @Override
    public TripDetailsRecord value17(Float value) {
        setTollamount(value);
        return this;
    }

    @Override
    public TripDetailsRecord value18(Float value) {
        setTotalamount(value);
        return this;
    }

    @Override
    public TripDetailsRecord value19(String value) {
        setVendorid(value);
        return this;
    }

    @Override
    public TripDetailsRecord values(String value1, Float value2, Float value3, LocalDateTime value4, String value5, Float value6, Float value7, Float value8, Float value9, Short value10, Short value11, LocalDateTime value12, String value13, Short value14, String value15, Float value16, Float value17, Float value18, String value19) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TripDetailsRecord
     */
    public TripDetailsRecord() {
        super(TripDetails.TRIP_DETAILS);
    }

    /**
     * Create a detached, initialised TripDetailsRecord
     */
    public TripDetailsRecord(String tripid, Float congestionsurcharge, Float distance, LocalDateTime dropoffdatetime, String dropofflocationid, Float extraamount, Float fareamount, Float improvementsurcharge, Float mtatax, Short passengercount, Short paymenttype, LocalDateTime pickupdatetime, String pickuplocationid, Short ratecodeid, String storeandfwdflag, Float tipamount, Float tollamount, Float totalamount, String vendorid) {
        super(TripDetails.TRIP_DETAILS);

        setTripid(tripid);
        setCongestionsurcharge(congestionsurcharge);
        setDistance(distance);
        setDropoffdatetime(dropoffdatetime);
        setDropofflocationid(dropofflocationid);
        setExtraamount(extraamount);
        setFareamount(fareamount);
        setImprovementsurcharge(improvementsurcharge);
        setMtatax(mtatax);
        setPassengercount(passengercount);
        setPaymenttype(paymenttype);
        setPickupdatetime(pickupdatetime);
        setPickuplocationid(pickuplocationid);
        setRatecodeid(ratecodeid);
        setStoreandfwdflag(storeandfwdflag);
        setTipamount(tipamount);
        setTollamount(tollamount);
        setTotalamount(totalamount);
        setVendorid(vendorid);
    }
}
